### ISSUE TITLE
Different package variants not working 

### ISSUE THREAD

**Issue by Thoromis** [lingohub/lh-android-docs#1]
Hey 👋 

I tried out your OTA SDK, but am having some trouble getting it to run for non-preproduction variants. The exact error log I am getting from the LingoHubLogger is [this](https://gist.github.com/Thoromis/8a42a5a8c0df6f70a96ce0dc499356c7).

When I add `setPreproductionEnabled` and switch back to the staging variant of the app, it works (I created to similar packages for this project in Lingohub, one pre-production and one production). 
Do you have an idea what the problem here could be?

**Comment by Thoromis** [comment]
I've found the issue - for anyone else encountering this, check your **proguard rules**. I had to add ``-keep class com.lingohub.** { *; }`` for it to work.

**Comment by sebastianmarschall** [comment]
Hey Thoromis,

thanks for reporting this issue. Since version _1.0.0-beta04_ you should no longer need to add this proguard rule.
